# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('value', models.DecimalField(decimal_places=8, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateField()),
                ('date_start', models.DateField()),
                ('list_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='er_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion_rates.ExchangeRateList'),
        ),
    ]
